servers : 
- name : server1
  url : https://www.youtube.com/
  alive : true
  max_request_per_server : 1000
- name : server2
  url : https://www.google.com/
  alive : true
  max_request_per_server : 1000
- name : server3
  url: http://localhost:8083
  alive : true 
  max_request_per_server : 1000

ServerConfig : 
  host : localhost
  port : 8080



LoadBalancerConfig :  
  algorithim : Round_robin 