servers : 
- name : server1
  url : http://localhost:8082
  alive : true
  max_request_per_server : 1000
- name : server2
  url : http://localhost:8081
  alive : true
  max_request_per_server : 1000
- name : server3
  url: http://localhost:8083
  alive : true 
  max_request_per_server : 1000



adminConfig : 
  host : localhost
  port : 8086

LoadBalancerConfig :  
  algorithim : Round_robin 
  host : localhost
  port : 8080